name: smartfarm_mobile
description: "A intregation app for doitung smartfarm"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_gen: ^5.10.0
  flutter_localizations:
    sdk: flutter

  # For Preferences
  shared_preferences: ^2.0.15

  # # For Google and Firebase
  # firebase_core: ^1.8.0
  # firebase_auth: ^3.1.4
  # firebase_auth_web: ^3.1.3
  # google_sign_in: ^5.2.0
  # firebase_crashlytics: ^2.2.4
  # firebase_performance: ^0.7.1+2
  
  # For Architecture
  hooks_riverpod: ^2.6.1
  provider: ^6.1.2
  url_launcher: ^6.1.10

  # For Translation
  intl: ^0.19.0
  
  # For Filesystem
  path: ^1.9.0
  path_provider: ^2.1.2
  external_path: ^1.0.3

  # For Excel Export
  excel: ^2.1.0

  # For Notification
  awesome_notifications: ^0.10.0
  
  # For UIs
  fl_chart: ^0.70.2
  cupertino_icons: ^1.0.8
  page_transition: ^2.1.0
  salomon_bottom_bar: ^3.3.2
  animated_custom_dropdown: ^3.1.1
  font_awesome_flutter: ^10.8.0
  syncfusion_flutter_charts: ^28.2.12
  shadcn_flutter: ^0.0.24
  lucide_icons: ^0.257.0
  bootstrap_icons: ^1.11.3
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.0.0
  flutter_gen_runner: ^5.10.0
  
  # For Translation
  intl_translation: ^0.20.1
  intl_utils: ^2.0.0

flutter:
  uses-material-design: true
  
  # ** Use flutter_gen instead of this ** 
  # dart run build_runner build
  generate: true
  assets:
    - assets/images/
  
flutter_gen:
  output: lib/gen/
  line_length: 80
  
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

  assets:
    enabled: true

flutter_intl:
  enabled: true
  class_name: L10n
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/gen_l10n
  use_deferred_loading: true